#Yet Another Markup Languages, TAB en la nueva línea
name: Ejemplo de Acciones
on: [push]
jobs:
  Primer-Github-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Bienvenido a GITHUB Actions"
      - run: echo "Ejecutando en ${{ runner.os }}"
      - run: echo "Datos de rama ${{ github.ref }} de ${{ github.repository }}"
    
    
